# Generated by Django 6.0.7 on 2026-08-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='level',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.level'),
        ),
    ]
