# Generated by Django 6.0.7 on 2026-07-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Premium subscription for PDF downloads'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_expiry',
            field=models.DateTimeField(blank=True, help_text='When premium subscription expires', null=True),
        ),
    ]
