# Generated by Django 6.0.7 on 2026-07-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_is_premium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Admin notes for verification'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
