# Generated by Django 4.2.26 on 2026-07-22 09:30
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_userprofile_id_document_userprofile_id_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='id_documents/', verbose_name='Identity Document'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_document_type',
            field=models.CharField(blank=True, choices=[('national_id', 'National ID Card'), ('school_id', 'School ID Card'), ('drivers_license', "Driver's License"), ('passport', 'International Passport')], max_length=20, null=True, verbose_name='Document Type'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='utility_bill',
            field=models.FileField(blank=True, null=True, upload_to='utility_bills/', verbose_name='Utility Bill (for address verification)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location_verified',
            field=models.BooleanField(default=False, verbose_name='Location Verified'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]