# Generated by Django 4.2.26 on 2026-07-22 10:00
from django.db import migrations

def convert_verified_to_approved(apps, schema_editor):
    UserProfile = apps.get_model('users', 'UserProfile')
    UserProfile.objects.filter(verification_status='verified').update(verification_status='approved')

class Migration(migrations.Migration):
    dependencies = [
        ('users', '0015_add_verification_fields'),
    ]
    operations = [
        migrations.RunPython(convert_verified_to_approved),
    ]