# Generated by Django 6.0.7 on 2026-07-22 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_userprofile_verification_status'),
    ]

    operations = [
    ]
