# Generated by Django 6.0.7 on 2026-07-22 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_convert_verified_to_approved'),
        ('users', '0017_convert_verified_to_approved'),
    ]

    operations = [
    ]
