# Generated by Django 6.0.7 on 2026-07-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_message_options_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, help_text="User's full name (e.g., CHE KENNETH)", max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='WhatsApp number for login and notifications', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.CharField(choices=[('primary', 'Primary School'), ('secondary', 'Secondary School'), ('university', 'University / Higher Institution'), ('', 'Not set')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='whatsappannouncement',
            name='target_audience',
            field=models.CharField(choices=[('all', 'All Users'), ('students', 'Students Only'), ('teachers', 'Teachers Only'), ('premium', 'Premium Users')], default='all', max_length=20),
        ),
    ]
