# Generated by Django 6.0.7 on 2026-07-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_userprofile_full_name_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, help_text="User's full name (e.g., CHE KENNETH)", max_length=200, null=True),
        ),
    ]
