# Generated by Django 6.0.7 on 2026-07-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.CharField(blank=True, choices=[('', 'Not set'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('technical', 'Technical & Vocational'), ('university', 'University'), ('higher', 'Higher Institute'), ('professional', 'Professional Certification'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
