services:
  - type: web
    name: skydemy
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    preDeployCommand: "python manage.py migrate"
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: skydemy-jeer.onrender.com
      - key: PYTHON_VERSION
        value: 3.12.9
      - key: DATABASE_URL
        fromDatabase:
          name: skydemy-db
          property: connectionString
    databases:
      - name: skydemy-db
        plan: free