# Generated by Django 6.0.7 on 2026-07-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_exam_exam_type_exam_level_exam_subject_exam_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_converted',
            field=models.BooleanField(default=False, help_text='True if this lesson was converted from a Word document'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='original_file',
            field=models.FileField(blank=True, help_text='Original uploaded file (for Word documents)', null=True, upload_to='lessons/originals/'),
        ),
    ]
