# Generated by Django 6.0.7 on 2026-08-01 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_add_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.exam'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
