# Generated by Django 6.0.7 on 2026-08-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_certificate_exam_certificate_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='cycle',
            field=models.CharField(blank=True, choices=[('first', 'First Cycle'), ('second', 'Second Cycle')], help_text='Cycle for secondary level only', max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'level')},
        ),
    ]
