# Generated by Django 6.0.7 on 2026-07-23 01:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lesson_is_converted_lesson_original_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='pdf_file',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload PDF lesson', max_length=255, null=True, verbose_name='PDF'),
        ),
    ]
