# Generated by Django 6.0.7 on 2026-08-02 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_subject_cycle_alter_subject_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
    ]
