# Generated by Django 6.0.7 on 2026-08-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_subject_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='year',
            field=models.CharField(blank=True, help_text='Year of the exam (e.g., 2024)', max_length=10, null=True),
        ),
    ]
