# Generated by Django 6.0.7 on 2026-07-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_subject_admin_notes_subject_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, help_text='Subject code (e.g., MATH101, PHY201)', max_length=20),
        ),
        migrations.AlterField(
            model_name='exam',
            name='admin_notes',
            field=models.TextField(blank=True, default='', help_text='Admin notes for review'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='admin_notes',
            field=models.TextField(blank=True, default='', help_text='Admin notes for review'),
        ),
    ]
