# Generated by Django 6.0.7 on 2026-07-24 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_subject_code_alter_exam_admin_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='code',
        ),
    ]
