# Generated by Django 6.0.7 on 2026-08-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_exam_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.JSONField(blank=True, default=list, help_text='List of question objects'),
        ),
    ]
