# Generated by Django 6.0.7 on 2026-08-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_exam_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='paper_number',
            field=models.CharField(blank=True, help_text='Paper number (e.g., Paper 1, Paper 2, etc.)', max_length=10, null=True),
        ),
    ]
