# Generated by Django 6.0.7 on 2026-07-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_subject_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, help_text='Subject code (e.g., MATH101, PHY201)', max_length=20, null=True),
        ),
    ]
