# Generated by Django 6.0.7 on 2026-07-24 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_subject_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name_plural': 'Progress'},
        ),
    ]
