# Generated by Django 6.0.7 on 2026-07-25 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_created_at_course_status_course_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Only approved subjects can be used.', null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.subject'),
        ),
    ]
