# Generated by Django 6.0.7 on 2026-07-25 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_lesson_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='exam',
            name='academic_session',
            field=models.CharField(blank=True, choices=[('2025/2026', '2025/2026'), ('2026/2027', '2026/2027'), ('2027/2028', '2027/2028')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='additional_resources',
            field=models.FileField(blank=True, null=True, upload_to='exams/resources/'),
        ),
        migrations.AddField(
            model_name='exam',
            name='answer_order',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('random', 'Randomized')], default='fixed', max_length=10),
        ),
        migrations.AddField(
            model_name='exam',
            name='attempts_allowed',
            field=models.PositiveIntegerField(default=1, help_text='Number of attempts allowed'),
        ),
        migrations.AddField(
            model_name='exam',
            name='auto_grade_objective',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='auto_submit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='browser_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='exam',
            name='disable_copy_paste',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='exam',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_code',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_document',
            field=models.FileField(blank=True, help_text='Upload exam paper (PDF/DOC/DOCX)', null=True, upload_to='exams/documents/'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_password',
            field=models.CharField(blank=True, help_text='Password required to access the exam', max_length=50),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_source',
            field=models.CharField(choices=[('online', 'Create Online Exam'), ('document', 'Upload Exam Document'), ('import', 'Import Question Bank')], default='online', max_length=10),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type_old',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='fullscreen_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='grading_method',
            field=models.CharField(choices=[('highest', 'Highest Score'), ('latest', 'Latest Attempt'), ('average', 'Average Score')], default='highest', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instructions to students (supports HTML)'),
        ),
        migrations.AddField(
            model_name='exam',
            name='ip_restriction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='exam',
            name='late_submission',
            field=models.BooleanField(default=False, help_text='Allow late submission'),
        ),
        migrations.AddField(
            model_name='exam',
            name='manual_review_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='marking_guide_document',
            field=models.FileField(blank=True, help_text='Upload marking guide (PDF/DOC/DOCX)', null=True, upload_to='exams/marking_guides/'),
        ),
        migrations.AddField(
            model_name='exam',
            name='marks_per_question',
            field=models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], default='auto', max_length=10),
        ),
        migrations.AddField(
            model_name='exam',
            name='negative_marking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='notify_after_grading',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='notify_before_deadline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='notify_immediately',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='notify_on_publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='number_of_questions',
            field=models.PositiveIntegerField(blank=True, help_text='Optional, auto-calculated if left blank', null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='passing_score_old',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='exam',
            name='question_order',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('random', 'Randomized')], default='fixed', max_length=10),
        ),
        migrations.AddField(
            model_name='exam',
            name='randomize_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='require_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='require_safe_browser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='require_webcam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='screen_recording',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='show_correct_answers',
            field=models.CharField(choices=[('immediately', 'Immediately'), ('after_due', 'After Due Date'), ('never', 'Never')], default='immediately', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='show_result_immediately',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='shuffle_options',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='shuffle_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='tab_switching_detection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='term',
            field=models.CharField(blank=True, choices=[('first', 'First Term'), ('second', 'Second Term'), ('third', 'Third Term'), ('semester_1', 'Semester I'), ('semester_2', 'Semester II')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Time limit for the exam, in minutes', null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='total_marks',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='exam',
            name='visibility',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='webcam_monitoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('class_test', 'Class Test'), ('assignment', 'Assignment'), ('ca', 'Continuous Assessment (CA)'), ('practical', 'Practical Test'), ('mock', 'Mock Exam'), ('mid_term', 'Mid-Term Examination'), ('end_term', 'End-of-Term Examination'), ('final', 'Final Examination'), ('entrance', 'Entrance Examination'), ('certification', 'Certification Exam')], default='quiz', max_length=50),
        ),
        migrations.AlterField(
            model_name='exam',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.lesson'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='passing_score',
            field=models.PositiveIntegerField(default=50, help_text='Percentage required to pass'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='questions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Only approved subjects can be used.', limit_choices_to={'status': 'approved'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.subject'),
        ),
    ]
