# Generated by Django 6.0.7 on 2026-07-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_exam_options_exam_academic_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='level',
            field=models.CharField(blank=True, choices=[('primary', 'Primary School'), ('secondary', 'Secondary School'), ('higher', 'Higher Institution / University')], max_length=20, null=True),
        ),
    ]
