# Generated by Django 6.0.7 on 2026-07-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_exam_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='exam',
            name='additional_resources',
            field=models.FileField(blank=True, help_text='Upload any additional resources (images, diagrams, etc.).', null=True, upload_to='exams/resources/'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='auto_grade_objective',
            field=models.BooleanField(default=True, help_text='Automatically grade objective questions (MCQ, True/False, etc.).'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='auto_submit',
            field=models.BooleanField(default=False, help_text='Automatically submit the exam when time runs out.'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='browser_lock',
            field=models.BooleanField(default=False, help_text='Lock the browser to prevent students from opening other tabs.'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='disable_copy_paste',
            field=models.BooleanField(default=False, help_text='Prevent students from copying or pasting text during the exam.'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_document',
            field=models.FileField(blank=True, help_text='Upload exam paper (PDF/DOC/DOCX).', null=True, upload_to='exams/documents/'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_password',
            field=models.CharField(blank=True, help_text="Password required to access the exam (if 'Require password' is enabled).", max_length=50),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_source',
            field=models.CharField(choices=[('online', 'Create Online Exam'), ('document', 'Upload Exam Document'), ('import', 'Import Question Bank')], default='online', help_text='How do you want to create this exam?', max_length=10),
        ),
        migrations.AlterField(
            model_name='exam',
            name='fullscreen_mode',
            field=models.BooleanField(default=False, help_text='Force students to take the exam in fullscreen mode.'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='grading_method',
            field=models.CharField(choices=[('highest', 'Highest Score'), ('latest', 'Latest Attempt'), ('average', 'Average Score')], default='highest', help_text='How to calculate the final grade if multiple attempts are allowed.', max_length=20),
        ),
        migrations.AlterField(
            model_name='exam',
            name='ip_restriction',
            field=models.BooleanField(default=False, help_text='Restrict access to specific IP addresses.'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='late_submission',
            field=models.BooleanField(default=False, help_text='Allow students to submit after the deadline.'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='manual_review_required',
            field=models.BooleanField(default=False, help_text='Require manual review before results are finalised.'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='marking_guide_document',
            field=models.FileField(blank=True, help_text='Upload marking guide (PDF/DOC/DOCX).', null=True, upload_to='exams/marking_guides/'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='marks_per_question',
            field=models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], default='auto', help_text='Assign marks automatically or manually per question.', max_length=10),
        ),
        migrations.AlterField(
            model_name='exam',
            name='negative_marking',
            field=models.BooleanField(default=False, help_text='Deduct marks for incorrect answers.'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='notify_after_grading',
            field=models.BooleanField(default=True, help_text='Send notification when grading is complete.'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='notify_before_deadline',
            field=models.BooleanField(default=False, help_text='Send reminder before the exam deadline.'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='notify_immediately',
            field=models.BooleanField(default=True, help_text='Send notification immediately when triggered.'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='notify_on_publish',
            field=models.BooleanField(default=True, help_text='Send notification when the exam is published.'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='randomize_questions',
            field=models.BooleanField(default=False, help_text='Randomise the order of questions for each student.'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='require_password',
            field=models.BooleanField(default=False, help_text='Require a password to access the exam.'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='require_safe_browser',
            field=models.BooleanField(default=False, help_text='Require a secure browser to take the exam.'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='require_webcam',
            field=models.BooleanField(default=False, help_text='Require a webcam to take the exam.'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='screen_recording',
            field=models.BooleanField(default=False, help_text="Record the student's screen during the exam."),
        ),
        migrations.AlterField(
            model_name='exam',
            name='show_correct_answers',
            field=models.CharField(choices=[('immediately', 'Immediately'), ('after_due', 'After Due Date'), ('never', 'Never')], default='immediately', help_text='When to show correct answers to students.', max_length=20),
        ),
        migrations.AlterField(
            model_name='exam',
            name='show_result_immediately',
            field=models.BooleanField(default=True, help_text='Show results to students as soon as they finish.'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='shuffle_options',
            field=models.BooleanField(default=False, help_text='Randomise the order of answer options for each student.'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='shuffle_questions',
            field=models.BooleanField(default=False, help_text='Randomise the order of questions for each student.'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='tab_switching_detection',
            field=models.BooleanField(default=False, help_text='Detect and log when a student switches tabs.'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='visibility',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Visibility status of the exam.', max_length=20),
        ),
        migrations.AlterField(
            model_name='exam',
            name='webcam_monitoring',
            field=models.BooleanField(default=False, help_text='Capture periodic snapshots during the exam.'),
        ),
    ]
