# Generated by Django 6.0.7 on 2026-07-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_examlike_unique_together_remove_examlike_exam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='level',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('technical', 'Technical & Vocational'), ('university', 'University'), ('higher', 'Higher Institute'), ('professional', 'Professional Certification'), ('other', 'Other')], default='primary', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('technical', 'Technical & Vocational'), ('university', 'University'), ('higher', 'Higher Institute'), ('professional', 'Professional Certification'), ('other', 'Other')], default='primary', max_length=20),
        ),
    ]
