# Generated by Django 6.0.7 on 2026-07-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_lesson_level_alter_subject_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='whiteboard_video',
            field=models.FileField(blank=True, help_text='Generated whiteboard video from the PDF.', null=True, upload_to='lessons/whiteboard_videos/'),
        ),
    ]
